baseurl = "https://www.bredley.co.uk"
title = "Bradley Garrod"
theme = "hugo-coder"

# Content
languagecode = "en"
defaultcontentlanguage = "en"
enableEmoji = true
paginate = 20
pygmentsStyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
    author = "Bradley Garrod"
    info = "Student developer and technology enthusiast"
    description = "Bradley Garrod's website"
    keywords = "blog,developer,programmer,java,university,student"
    avatarurl = "images/me.jpg"


    favicon_32 = "favicon-32x32.png"
    favicon_16 = "favicon-16x16.png"

    inverted = true
    footercontent = ""

    hidecredits = true
    hidecopyright = true

    math = true
    custom_css = ["css/custom.css"]

# Social links
[[params.social]]
    name = "Github"
    icon = "fab fa-github"
    weight = 1
    url = "https://github.com/BreD1810/"
[[params.social]]
    name = "Gitlab"
    icon = "fab fa-gitlab"
    weight = 2
    url = "https://gitlab.com/BreD1810/"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin"
    weight = 3
    url = "https://www.linkedin.com/in/bradley-garrod-861283175/"

# Menu links
[[menu.main]]
    name = "About"
    weight = 1
    url = "/about/"
[[menu.main]]
    name = "Portfolio"
    weight = 2
    url = "/portfolio/"
[[menu.main]]
    name = "Blog"
    weight = 3
    url  = "/posts/"
[[menu.main]]
    name = "Contact"
    weight = 4
    url = "/contact/"
